install:
  - ps: |
        $version = [version]$(cat VERSION)
        $build = $env:APPVEYOR_BUILD_NUMBER
        $major = $version.Major

        $branch = $env:APPVEYOR_REPO_BRANCH
        if ($branch -eq 'master') {
          $version = "$version-ci-$build"
        }
        else {
          $version = "$version-branch-$branch-$build"
        }
        Set-AppveyorBuildVariable -Name "AssemblyMajor" -Value "$major"
        Update-AppVeyorBuild -Version "$version"

assembly_info:
  patch: true
  file: src\CommonInfo.cs
  assembly_version: $(AssemblyMajor).0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'


configuration: Release

platform: Any CPU

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test:
  assemblies: src\OpenRasta.Hosting.AspNet.Tests.Integration\bin\$(configuration)\OpenRasta.Hosting.AspNet.Tests.Integration.dll

artifacts:
- path: src\OpenRasta.Hosting.AspNet\bin\$(configuration)\*.dll
  name: dlls
- path: src\OpenRasta.Hosting.AspNet\bin\$(configuration)\*.pdb
  name: pdbs
