version: 2.5.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: src\CommonInfo.cs
  assembly_version: 2.0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies: src\OpenRasta.Hosting.AspNet.Tests.Integration\bin\$(configuration)\OpenRasta.Hosting.AspNet.Tests.Integration.dll
artifacts:
- path: src\OpenRasta.Hosting.AspNet\bin\$(configuration)\*.dll
  name: dlls
- path: src\OpenRasta.Hosting.AspNet\bin\$(configuration)\*.pdb
  name: pdbs
- path: '*.nupkg'
  name: Nuget