configuration: Release
image: Visual Studio 2017

install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - ps: $AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols"
  - ps: mkdir c:\ca; iwr https://curl.haxx.se/ca/cacert.pem -outfile C:\ca\cacert.pem
  - set SSL_CERT_FILE=C:\ca\cacert.pem
  - ps: |
        $version = [version]$(cat VERSION)
        $build = $env:APPVEYOR_BUILD_NUMBER
        $major = $version.Major
        
        $branch = $env:APPVEYOR_REPO_BRANCH
        if ($branch -eq 'master') {
          $version = "$version-ci-$build"
        } elseif ($env:APPVEYOR_REPO_TAG -eq "true") {
          $version = $env:APPVEYOR_REPO_TAG_NAME
        } elseif ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
          $version = "$version-pr-$env:APPVEYOR_PULL_REQUEST_NUMBER-$build"
        } else {
          $version = "$version-br-$branch-$build"
        }
        Set-AppveyorBuildVariable -Name "AssemblyMajor" -Value "$major"
        Update-AppVeyorBuild -Version "$version"
        Write-Output "$version"
        if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          gem install chandler --no-ri --no-rdoc
          set-content ~/.netrc "machine api.github.com login $env:github_username password $env:github_password" -encoding ascii
          cp ~/.netrc ~/_netrc
          chandler push
        }


dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: $(AssemblyMajor).0.0.0
  file_version: '{version}'
  informational_version: '{version}'


environment:
  SSL_CERT_FILE: C:\ca\cacert.pem
  github_username: serialseb
  github_password:
    secure:
      1lXaOJ0GvCAOd0O9DDvVqw2eb7TvP2jve12u3hD2g4J7RVW2c2jC5XuRFyEuduUA


nuget:
  project_feed: true
  disable_publish_on_pr: true


before_build:
  - cd .\src\  
  - dotnet restore --verbosity Minimal

build_script:
  - dotnet build --configuration %CONFIGURATION%  

test_script:
  - dotnet test .\OpenRasta.Hosting.AspNet.Tests.Integration\
  - dotnet test .\Tests\

after_build:
  - dotnet pack .\OpenRasta.Hosting.AspNet --include-symbols --configuration %CONFIGURATION% --no-build 


artifacts:
- path: src\OpenRasta.Hosting.AspNet\bin\$(configuration)\*.dll
  name: dlls
- path: src\OpenRasta.Hosting.AspNet\bin\$(configuration)\*.pdb
  name: pdbs
- path: "*.nupkg"
  name: nuget
