version: 2.5.{build}
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: 2.0.0.0
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

build:
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

artifacts:
- path: src\OpenRasta.DI.Windsor\bin\$(configuration)\net461\*.dll
  name: dlls
- path: src\OpenRasta.DI.Windsor\bin\$(configuration)\net461\*.pdb
  name: pdbs